Да, finally, вызывается после выполнения блоков try или catch.

Единственными моментами, которые, finally, не будут вызываться, являются:


1. Если вы вызываете System.exit();
2. Если сначала произойдет сбой JVM;
3. Если JVM достигает бесконечного цикла (или другого не прерывающегося, не заканчивающегося оператора) в блоке try или catch;
4. Если ОС принудительно завершает процесс JVM; например, "убить -9" в UNIX.
5. Если хост-система умирает; например, сбой питания, аппаратная ошибка, паника ОС и т.д.
6. Если, наконец, блок будет выполняться потоком демона, а все остальные не-демонные потоки выходят до того, как, наконец, вызывается.